Repository hook-killer/back-end, pull requests merged in 2023-10, with the labels that each got.

#3 [CHORE] 빌드 및 프로젝트 기본 셋팅
  .gitattributes
  .github/workflows/CI.yml
  Dockerfile
  README.md
  build.gradle
  libs/nelo2-java-sdk-core-1.6.6.jar
  libs/nelo2-java-sdk-log4j2-2.8.5.jar
  libs/nelo2-java-sdk-logback-1.6.6.jar
  src/main/java/HookKiller/server/ServerApplication.java
  src/main/java/HookKiller/server/common/controller/HealthCheckController.java
  src/main/java/HookKiller/server/common/dto/ErrorDetail.java
  src/main/java/HookKiller/server/common/exception/BaseErrorCode.java
  src/main/java/HookKiller/server/common/exception/BaseException.java
  src/main/java/HookKiller/server/common/exception/ExampleException.java
  src/main/java/HookKiller/server/common/exception/GlobalException.java
  src/main/java/HookKiller/server/config/AsyncConfig.java
  src/main/java/HookKiller/server/config/ConfigurationProperties.java
  src/main/java/HookKiller/server/config/JPAAuditingConfig.java
  src/main/java/HookKiller/server/config/SchedulingConfig.java
  src/main/java/HookKiller/server/config/security/CorsConfig.java
  src/main/java/HookKiller/server/config/security/SecurityConfig.java
  src/main/java/HookKiller/server/properties/.keep
  src/main/resources/application-db.yml
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
  src/main/resources/application-security.yml
  src/main/resources/application.properties
  src/main/resources/application.yml
  src/main/resources/config/logback/logback-dev.xml
  src/main/resources/data.sql
  src/main/resources/static/.keep
  src/main/resources/templates/.keep
  src/test/java/HookKiller/server/.keep
  src/test/java/HookKiller/server/ServerApplicationTests.java
Labels: enhancement

#16 [FEATURE] User Entity & Repository 작성 / Security & JWT 관련 작성
  build.gradle
  src/main/java/HookKiller/server/ServerApplication.java
  src/main/java/HookKiller/server/common/AbstractTimeStamp.java
  src/main/java/HookKiller/server/common/exception/ExpiredTokenException.java
  src/main/java/HookKiller/server/common/exception/GlobalException.java
  src/main/java/HookKiller/server/common/exception/InvalidTokenException.java
  src/main/java/HookKiller/server/config/ConfigurationProperties.java
  src/main/java/HookKiller/server/config/auth/CustomUserDetails.java
  src/main/java/HookKiller/server/config/auth/CustomUserDetailsService.java
  src/main/java/HookKiller/server/config/controller/AuthController.java
  src/main/java/HookKiller/server/config/security/SecurityConfig.java
  src/main/java/HookKiller/server/jwt/JwtAuthenticationEntryPoint.java
  src/main/java/HookKiller/server/jwt/JwtAuthenticationFilter.java
  src/main/java/HookKiller/server/jwt/JwtTokenProvider.java
  src/main/java/HookKiller/server/properties/.keep
  src/main/java/HookKiller/server/properties/JwtProperties.java
  src/main/java/HookKiller/server/user/controller/UserController.java
  src/main/java/HookKiller/server/user/dto/request/UserLoginDto.java
  src/main/java/HookKiller/server/user/entity/CertificateKey.java
  src/main/java/HookKiller/server/user/entity/User.java
  src/main/java/HookKiller/server/user/repository/UserRepository.java
  src/main/java/HookKiller/server/user/service/UserService.java
  src/main/java/HookKiller/server/user/type/LoginType.java
  src/main/java/HookKiller/server/user/type/Status.java
  src/main/java/HookKiller/server/user/type/UserRole.java
  src/main/resources/application-local.yml
  src/main/resources/application.yml
  src/main/resources/data.sql
Labels: enhancement

#17 Feat/14 admin page
  src/main/java/HookKiller/server/common/type/LanguageType.java
  src/main/java/HookKiller/server/common/type/NoticeArticleStatus.java
  src/main/java/HookKiller/server/notice/entity/NoticeArticle.java
  src/main/java/HookKiller/server/notice/entity/NoticeContent.java
  src/main/java/HookKiller/server/repository/NoticeArticleRepository.java
  src/main/java/HookKiller/server/repository/NoticeContentRepository.java
Labels: enhancement

#23 [FEATURE] 회원가입 API 구현
  src/main/java/HookKiller/server/auth/controller/AuthController.java
  src/main/java/HookKiller/server/auth/dto/request/RegisterRequest.java
  src/main/java/HookKiller/server/auth/service/AuthService.java
  src/main/java/HookKiller/server/user/dto/request/UserLoginDto.java
  src/main/java/HookKiller/server/user/entity/User.java
  src/main/java/HookKiller/server/user/exception/AlreadyExistUserException.java
  src/main/java/HookKiller/server/user/exception/UserException.java
  src/main/java/HookKiller/server/user/repository/UserRepository.java
  src/main/java/HookKiller/server/user/service/UserService.java
Labels: enhancement

#20 Feat/10 board - 게시판 entity , repo 작성
  .gitignore
  build.gradle
  src/main/java/HookKiller/server/board/controller/ArticleController.java
  src/main/java/HookKiller/server/board/dto/ArticleRequestDto.java
  src/main/java/HookKiller/server/board/dto/PostArticleRequestDto.java
  src/main/java/HookKiller/server/board/entity/Article.java
  src/main/java/HookKiller/server/board/entity/ArticleContent.java
  src/main/java/HookKiller/server/board/entity/ArticleLike.java
  src/main/java/HookKiller/server/board/entity/Board.java
  src/main/java/HookKiller/server/board/entity/Reply.java
  src/main/java/HookKiller/server/board/entity/ReplyContent.java
  src/main/java/HookKiller/server/board/exception/ArticleContentNotFoundException.java
  src/main/java/HookKiller/server/board/exception/BoardException.java
  src/main/java/HookKiller/server/board/exception/BoardNotFoundException.java
  src/main/java/HookKiller/server/board/repository/ArticleContentRepository.java
  src/main/java/HookKiller/server/board/repository/ArticleRepository.java
  src/main/java/HookKiller/server/board/repository/BoardRepository.java
  src/main/java/HookKiller/server/board/repository/ReplyContentRepository.java
  src/main/java/HookKiller/server/board/repository/ReplyRepository.java
  src/main/java/HookKiller/server/board/service/ArticleContentService.java
  src/main/java/HookKiller/server/board/service/ArticleService.java
  src/main/java/HookKiller/server/board/type/ArticleStatus.java
  src/main/java/HookKiller/server/board/type/BoardType.java
  src/main/java/HookKiller/server/common/controller/HealthCheckController.java
  src/main/java/HookKiller/server/common/controller/PapagoSampleController.java
  src/main/java/HookKiller/server/common/dto/PapagoHtmlRequest.java
  src/main/java/HookKiller/server/common/dto/PapagoHtmlResponse.java
  src/main/java/HookKiller/server/common/dto/PapagoTextRequest.java
  src/main/java/HookKiller/server/common/dto/PapagoTextResponse.java
  src/main/java/HookKiller/server/common/dto/TranslateResponseDto.java
  src/main/java/HookKiller/server/common/exception/GlobalException.java
  src/main/java/HookKiller/server/common/exception/NaverErrorException.java
  src/main/java/HookKiller/server/common/service/TranslateService.java
  src/main/java/HookKiller/server/common/type/LanguageType.java
  src/main/java/HookKiller/server/config/ConfigurationProperties.java
  src/main/java/HookKiller/server/properties/NaverObjectStorageProperties.java
  src/main/java/HookKiller/server/properties/PapagoProperties.java
  src/main/resources/application-local.yml
  src/main/resources/application-papago.yml
  src/main/resources/application.yml
Labels: enhancement

#19 feat: controller, service 수정 #14
  src/main/java/HookKiller/server/common/AbstractTimeStamp.java
  src/main/java/HookKiller/server/common/type/ArticleStatus.java
  src/main/java/HookKiller/server/common/type/LanguageType.java
  src/main/java/HookKiller/server/notice/controller/NoticeController.java
  src/main/java/HookKiller/server/notice/dto/AddNoticeRequest.java
  src/main/java/HookKiller/server/notice/dto/EditNoticeRequest.java
  src/main/java/HookKiller/server/notice/dto/NoticeArticleDto.java
  src/main/java/HookKiller/server/notice/entity/NoticeArticle.java
  src/main/java/HookKiller/server/notice/entity/NoticeContent.java
  src/main/java/HookKiller/server/notice/exception/NoticeException.java
  src/main/java/HookKiller/server/notice/exception/NoticeNotAdminForbiddenException.java
  src/main/java/HookKiller/server/notice/exception/NoticeNotFoundException.java
  src/main/java/HookKiller/server/notice/repository/NoticeArticleRepository.java
  src/main/java/HookKiller/server/notice/repository/NoticeContentRepository.java
  src/main/java/HookKiller/server/notice/service/NoticeService.java
  src/main/java/HookKiller/server/repository/NoticeArticleRepository.java
  src/main/resources/application-local.yml
  src/main/resources/data.sql
Labels: enhancement

#33 feat : 게시판 단건조회 기능 구현
  src/main/java/HookKiller/server/board/controller/ArticleController.java
  src/main/java/HookKiller/server/board/repository/ArticleRepository.java
  src/main/java/HookKiller/server/board/service/ArticleService.java
  src/main/resources/application-local.yml
Labels: enhancement

#34 [FEATURE] reply 기능 구현 완료
  src/main/java/HookKiller/server/board/controller/ReplyController.java
  src/main/java/HookKiller/server/board/dto/ReplyResponseDto.java
  src/main/java/HookKiller/server/board/entity/Reply.java
  src/main/java/HookKiller/server/board/entity/ReplyContent.java
  src/main/java/HookKiller/server/board/exception/BoardException.java
  src/main/java/HookKiller/server/board/exception/ReplyContentNotFoundException.java
  src/main/java/HookKiller/server/board/repository/ArticleRepository.java
  src/main/java/HookKiller/server/board/repository/ReplyContentRepository.java
  src/main/java/HookKiller/server/board/repository/ReplyRepository.java
  src/main/java/HookKiller/server/board/service/ArticleContentService.java
  src/main/java/HookKiller/server/board/service/ArticleService.java
  src/main/java/HookKiller/server/board/service/ReplyService.java
  src/main/java/HookKiller/server/board/type/ReplyStatus.java
  src/main/java/HookKiller/server/common/service/TranslateService.java
  src/main/resources/application-local.yml
Labels: enhancement

#44 feat : 게시물 좋아요 기능 구현
  src/main/java/HookKiller/server/board/controller/ArticleLikeController.java
  src/main/java/HookKiller/server/board/entity/Article.java
  src/main/java/HookKiller/server/board/entity/ArticleLike.java
  src/main/java/HookKiller/server/board/repository/ArticleLikeRepository.java
  src/main/java/HookKiller/server/board/service/ArticleLikeService.java
  src/main/java/HookKiller/server/board/type/ArticleLikeConstants.java
  src/main/java/HookKiller/server/common/dto/CommonBooleanResultResponse.java
  src/main/java/HookKiller/server/common/exception/DeleteFailException.java
  src/main/java/HookKiller/server/common/exception/GlobalException.java
  src/main/java/HookKiller/server/common/util/UserUtils.java
  src/main/java/HookKiller/server/user/exception/UserException.java
  src/main/java/HookKiller/server/user/exception/UserNotActiveException.java
Labels: enhancement

#35 [FEATURE] 계정관리 페이지 기능 구현중
  src/main/java/HookKiller/server/admin/controller/AdminController.java
  src/main/java/HookKiller/server/admin/dto/AccountSearchResponse.java
  src/main/java/HookKiller/server/admin/dto/AccountStatusRequestDto.java
  src/main/java/HookKiller/server/admin/exception/AdminException.java
  src/main/java/HookKiller/server/admin/exception/UserNotAdminException.java
  src/main/java/HookKiller/server/admin/service/AdminService.java
  src/main/java/HookKiller/server/board/dto/ArticleRequestDto.java
  src/main/java/HookKiller/server/board/entity/ArticleContent.java
  src/main/java/HookKiller/server/board/repository/ArticleContentRepository.java
  src/main/java/HookKiller/server/board/repository/ArticleRepository.java
  src/main/java/HookKiller/server/board/repository/ReplyRepository.java
  src/main/java/HookKiller/server/board/service/ReplyService.java
  src/main/java/HookKiller/server/common/util/UserUtils.java
  src/main/java/HookKiller/server/notice/service/NoticeService.java
  src/main/java/HookKiller/server/user/dto/UserDto.java
  src/main/java/HookKiller/server/user/entity/User.java
  src/main/java/HookKiller/server/user/exception/UserAccountNotActiveException.java
  src/main/java/HookKiller/server/user/exception/UserException.java
  src/main/java/HookKiller/server/user/exception/UserNotActiveException.java
  src/main/java/HookKiller/server/user/repository/UserRepository.java
Labels: enhancement

#42 feat : 마이페이지 기능 구현
  src/main/java/HookKiller/server/admin/service/AdminService.java
  src/main/java/HookKiller/server/auth/service/AuthService.java
  src/main/java/HookKiller/server/board/repository/ArticleContentRepository.java
  src/main/java/HookKiller/server/board/repository/ArticleLikeRepository.java
  src/main/java/HookKiller/server/common/exception/BadTypeRequestException.java
  src/main/java/HookKiller/server/common/exception/GlobalException.java
  src/main/java/HookKiller/server/common/util/SecurityUtils.java
  src/main/java/HookKiller/server/user/controller/MypageController.java
  src/main/java/HookKiller/server/user/dto/MyPageUserResponse.java
  src/main/java/HookKiller/server/user/dto/MyPageUserUpdateRequest.java
  src/main/java/HookKiller/server/user/entity/User.java
  src/main/java/HookKiller/server/user/exception/UserException.java
  src/main/java/HookKiller/server/user/exception/UserUpdateUnAuthorizedException.java
  src/main/java/HookKiller/server/user/service/MyPageService.java
  src/main/java/HookKiller/server/user/service/UserService.java
Labels: enhancement

#50 [FEATURE] 자체 검색 기능을 구현합니다.
  build.gradle
  src/main/java/HookKiller/server/board/dto/ArticleRequestDto.java
  src/main/java/HookKiller/server/board/repository/ArticleContentRepository.java
  src/main/java/HookKiller/server/board/repository/ArticleRepository.java
  src/main/java/HookKiller/server/search/controller/SearchController.java
  src/main/java/HookKiller/server/search/dto/KeyDownArticleDto.java
  src/main/java/HookKiller/server/search/exception/SearchArticleContentNotFoundException.java
  src/main/java/HookKiller/server/search/exception/SearchArticleNotFoundException.java
  src/main/java/HookKiller/server/search/exception/SearchException.java
  src/main/java/HookKiller/server/search/service/SearchService.java
Labels: enhancement

#53 [FIX, FEATURES] 전체 이슈 수정
  src/main/java/HookKiller/server/admin/controller/AdminController.java
  src/main/java/HookKiller/server/admin/service/AdminService.java
  src/main/java/HookKiller/server/auth/dto/request/SingUpRequest.java
  src/main/java/HookKiller/server/board/dto/ArticleRequestDto.java
  src/main/java/HookKiller/server/board/dto/ReplyResponseDto.java
  src/main/java/HookKiller/server/board/entity/ArticleContent.java
  src/main/java/HookKiller/server/board/entity/ArticleLike.java
  src/main/java/HookKiller/server/board/entity/Reply.java
  src/main/java/HookKiller/server/board/service/ReplyService.java
  src/main/java/HookKiller/server/common/util/UserUtils.java
  src/main/java/HookKiller/server/config/security/SecurityConfig.java
  src/main/java/HookKiller/server/notice/dto/NoticeArticleDto.java
  src/main/java/HookKiller/server/notice/service/NoticeService.java
  src/main/java/HookKiller/server/user/controller/MypageController.java
  src/main/java/HookKiller/server/user/dto/MyPageUserUpdateRequest.java
  src/main/java/HookKiller/server/user/dto/UserDto.java
  src/main/java/HookKiller/server/user/service/MyPageService.java
  src/main/java/HookKiller/server/user/service/UserService.java
  src/main/resources/data.sql
Labels: enhancement

#55 [FEATURE] 인기 게시물 조회 기능 구현
  src/main/java/HookKiller/server/board/controller/ArticleController.java
  src/main/java/HookKiller/server/board/dto/PopularArticleResponse.java
  src/main/java/HookKiller/server/board/repository/ArticleRepository.java
  src/main/java/HookKiller/server/board/service/ArticleService.java
  src/main/java/HookKiller/server/config/feign/FeignCommonConfig.java
  src/main/java/HookKiller/server/config/security/SecurityConfig.java
Labels: enhancement

#56 [FEATURE] 페이지네이션에 필요한 api 추가
  src/main/java/HookKiller/server/board/repository/ArticleRepository.java
  src/main/java/HookKiller/server/search/controller/SearchController.java
  src/main/java/HookKiller/server/search/service/SearchService.java
Labels: enhancement

#60 fix : Dockefile 변경!
  Dockerfile
Labels: wontfix

#62 [FIX] reply 관련 dto, security 설정, api 일부 수정 혹은 추가
  src/main/java/HookKiller/server/board/controller/ReplyController.java
  src/main/java/HookKiller/server/board/dto/PostReplyRequestDto.java
  src/main/java/HookKiller/server/board/dto/ReplyResponseDto.java
  src/main/java/HookKiller/server/board/entity/ArticleContent.java
  src/main/java/HookKiller/server/board/entity/ReplyContent.java
  src/main/java/HookKiller/server/board/service/ArticleService.java
  src/main/java/HookKiller/server/board/service/ReplyService.java
  src/main/java/HookKiller/server/board/type/ReplyStatus.java
  src/main/java/HookKiller/server/config/security/SecurityConfig.java
  src/main/resources/application-local.yml
  src/main/resources/data.sql
Labels: bug, enhancement

#67 [FIX] 타국어로 텍스트 입력시 Html 번역 이슈
  src/main/java/HookKiller/server/board/controller/ArticleController.java
  src/main/java/HookKiller/server/board/service/ArticleService.java
  src/main/java/HookKiller/server/common/controller/PapagoSampleController.java
  src/main/java/HookKiller/server/common/service/TranslateService.java
  src/main/java/HookKiller/server/config/security/SecurityConfig.java
  src/main/java/HookKiller/server/notice/dto/EditNoticeRequest.java
  src/main/java/HookKiller/server/notice/service/NoticeService.java
  src/main/resources/application-local.yml
Labels: bug

#69 feat : 공지사항 리스트 페이징 처리
  src/main/java/HookKiller/server/notice/controller/NoticeController.java
  src/main/java/HookKiller/server/notice/service/NoticeService.java
Labels: enhancement

#70 [REFACTOR] papago RestTemplate Connection Pool 구현
  build.gradle
  src/main/java/HookKiller/server/common/service/TranslateService.java
  src/main/java/HookKiller/server/common/util/HtmlTranslateRestTemplate.java
  src/main/java/HookKiller/server/common/util/TextTranslateRestTemplate.java
Labels: refactor

#72 [REFACTOR] papago 번역 이슈 해결
  src/main/java/HookKiller/server/board/service/ArticleService.java
  src/main/java/HookKiller/server/notice/service/NoticeService.java
Labels: bug

#73 [FEATURE] userInfo 생성일 추가
  src/main/java/HookKiller/server/user/dto/MyPageUserResponse.java
  src/main/resources/application-local.yml
Labels: enhancement

#80 [refactor] 백엔드 이슈수정 및 코드정리중
  src/main/java/HookKiller/server/auth/helper/KakaoOauthHelper.java
  src/main/java/HookKiller/server/auth/helper/OIDCHelper.java
  src/main/java/HookKiller/server/board/service/ArticleLikeService.java
  src/main/java/HookKiller/server/board/service/ReplyService.java
  src/main/java/HookKiller/server/common/AbstractTimeStamp.java
  src/main/java/HookKiller/server/common/util/UserUtils.java
  src/main/java/HookKiller/server/jwt/JwtAuthenticationEntryPoint.java
  src/main/java/HookKiller/server/jwt/JwtAuthenticationFilter.java
  src/main/java/HookKiller/server/jwt/JwtOIDCProvider.java
  src/main/resources/application-db.yml
Labels: bug, enhancement, wontfix, refactor

#95 fix : 썸네일 추가
  src/main/java/HookKiller/server/auth/dto/response/AuthResponse.java
  src/main/java/HookKiller/server/auth/service/AuthService.java
  src/main/resources/data.sql
Labels: bug, enhancement, wontfix

#102 [FIX] 마이페이지 페이징 처리
  src/main/java/HookKiller/server/common/AbstractTimeStamp.java
  src/main/java/HookKiller/server/user/service/MyPageService.java
Labels: bug, wontfix
